server:
    port: 8081

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost/realms/oauth2
                    jwk-set-uri: http://localhost/realms/oauth2/protocol/openid-connect/certs
                    